name: Techorganic Dot Com
description: Musings from the brainpan
meta_description: "Musings from the brainpan"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
permalink: /:year/:month/:day/:title/
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: techorganic

# Details for the RSS feed generator
url:            'http://www.techorganic.com'
author:         'superkojiman'
